"use client";

import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    // ——— Nav ———
    home: "Home",
    attractions: "Attractions",
    addAttraction: "+ Add Attraction",
    browseAttractions: "Browse Attractions",
    map: "Map",
    travellers: "Travellers",
    community: "Community",
    myProfile: "My Profile",
    logout: "Logout",
    signIn: "Sign in",
    menu: "Menu",

    // ——— Common ———
    loading: "Loading...",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    back: "Back",
    backToExplore: "Back to explore",
    backToProfile: "Back to Profile",
    search: "Search",
    reset: "Reset",
    submit: "Submit",
    close: "Close",
    yes: "Yes",
    no: "No",
    remove: "Remove",
    errorGeneric: "Something went wrong. Please try again.",
    unauthorized: "Please sign in to continue.",
    notFound: "Page not found",

    // ——— Login ———
    loginSubtitle:
      "Sign in to save places, write reviews, and manage your profile",
    loginGuestHint:
      "You can still browse attractions, the map, and community as a guest.",
    signInWithGoogle: "Sign in with Google",
    signingIn: "Signing in...",
    continueAsGuest: "Continue browsing as guest",
    termsAgree: "By continuing, you agree to our Terms of Service",
    googleAuthFailed: "Google authentication failed. Please try again.",

    // ——— Home hero ———
    heroEyebrow: "Explore Melaka with the community",
    heroTitle: "Discover attractions and record your travel journey",
    heroSubtitle:
      "Browse popular and lesser-known attractions, read traveller experiences and start exploring Melaka.",

    // ——— Search / filters ———
    searchAttractions: "Search Attractions",
    searchPlaceholder: "Search attractions in Melaka",
    moreFilters: "More Filters",
    hideFilters: "Hide Filters",
    minimumRating: "Minimum Rating",
    anyRating: "Any Rating",
    ratingAndAbove: "and above",
    locationArea: "Location Area",
    allAreas: "All Areas",
    sortBy: "Sort by",
    sortNameAsc: "Name (A-Z)",
    sortRating: "Rating",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    sortMostReviewed: "Most Reviewed",
    sortLowestRating: "Lowest Rating",
    source: "Source",
    allAttractions: "All Attractions",
    communitySubmittedOnly: "Community-submitted only",
    allCategories: "All Categories",
    attractionsAvailable: "{count} attraction(s) available",
    resultsFound: "{count} result(s) found for {criteria}",
    loadingAttractions: "Loading attractions...",
    failedLoadAttractions: "Failed to load attractions. Please try again.",
    noAttractionsFound: "No attractions found",
    tryChangingFilters:
      "Try changing the keyword, category, area, rating, or clear all filters.",
    clearSearchAndFilters: "Clear Search and Filters",
    previous: "Previous",
    next: "Next",
    pageOf: "Page {page} of {total}",
    keyword: "keyword",
    category: "category",
    area: "area",
    rating: "rating",

    // ——— Categories ———
    cat_All: "All Categories",
    cat_Museum: "Museum",
    cat_Religious: "Religious",
    cat_TouristAttraction: "Tourist Attraction",
    cat_Historical: "Historical",
    cat_Nature: "Nature",
    cat_Entertainment: "Entertainment",
    cat_Gallery: "Gallery",

    // ——— Attraction detail / actions ———
    details: "Details",
    address: "Address",
    description: "Description",
    photos: "Photos",
    reviews: "Reviews",
    writeReview: "Write a review",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    addToFavourites: "Add to Favourites",
    removeFromFavourites: "Remove from Favourites",
    signInToSave: "Sign in to save this place",
    signInToReview: "Sign in to write a review",
    editDescription: "Edit description",
    saveDescription: "Save description",
    onlyMelakaCanEdit:
      "Only users whose home state is Melaka can edit descriptions.",
    uploadPhoto: "Upload photo",
    noFileChosen: "No file chosen",
    noPhotosYet: "No photos yet",
    noReviewsYetAttraction: "No reviews yet",
    communitySubmitted: "Community submitted",
    openInMaps: "Open in Google Maps",
    aboutAttraction: "About Description",
    descriptionPlaceholder:
      "Share what makes this attraction worth visiting…",
    noDescription: "No description available for this attraction yet.",
    sourceWikipedia: "Source: Wikipedia",
    melakaOnlyFeature: "Available to Melaka-based users",
    addPhoto: "Add Photo",
    photoAddedThanks: "Photo added — thanks for contributing!",

    // ——— Verified visitor photos ———
    verifiedVisitorPhotos: "Verified Visitor Photos",
    verifiedVisitorPhotosHint:
      "Public on-site photos shared by travellers who verified their visit.",
    noVerifiedPhotos: "No verified visitor photos yet.",
    verifiedVisit: "Verified Visit",
    loadingVerifiedPhotos: "Loading verified visitor photos...",
    refreshVerifiedPhotos: "Refreshing verified visitor photos...",
    refreshVerifiedFailed:
      "The latest verified visitor photos could not be loaded. The current photos are preserved below.",
    retryRefresh: "Retry refresh",
    signInManageVerified:
      "Sign in to manage your verified visitor photos.",
    signInManageVerifiedHint:
      "Your photos remain public, but deletion requires a signed-in owner session.",
    reloadPhotos: "Reload photos",
    deleteVerifiedPhotoConfirm:
      "Delete this verified visitor photo? This action cannot be undone.",
    deletingPhoto: "Deleting photo...",
    tryDeleteAgain: "Try delete again",
    deletePhoto: "Delete photo",

    // ——— Map extras (for later components) ———
    verifyNearbyPlace: "Verify a nearby place",
    verifyNearbyVisit: "Verify Nearby Visit",
    verifyNearbyHint:
      "When you start, Chatlas checks your current location once and then opens your live camera. It does not track your movement.",
    showLiveLocation: "Show my live location",
    liveLocationHint:
      "When enabled, the map shows your position while this page is open. Location stays on this device and is not stored or uploaded.",
    explorationProgress: "Exploration progress",
    visitedAttractions: "Visited attractions",
    noVisitedYet: "No visited attractions yet",
    visitedListHint:
      "Attractions confirmed through a verified visit will appear in this list.",
    visitedCountLabel: "{count} visited",
    ofAttractionsVisited: "{visited} of {total} attractions visited",
    newExplorer: "New explorer",
    personalExploration: "Personal exploration",

    // ——— Add attraction ———
    addAttractionTitle: "Add Attraction",
    attractionName: "Name",
    attractionCategory: "Category",
    attractionAddress: "Address",
    attractionDescriptionOptional: "Description (optional)",
    submitAttraction: "Submit attraction",
    submitSuccess: "Attraction submitted successfully",
    submitFailed: "Failed to submit attraction",
    signInToAddAttraction: "Sign in to add an attraction",

    // ——— Profile ———
    editProfile: "Edit Profile",
    displayName: "Display name",
    email: "Email",
    location: "Location",
    homeState: "Home state",
    selectStateTerritory: "Select state / territory",
    locationLegacyHint:
      'Previous value "{value}" is not in the list. Please choose a state or territory above.',
    melakaEditHint: "You can edit Melaka attraction descriptions.",
    bio: "Bio",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated successfully!",
    placesVisited: "Places visited",
    reviewsWritten: "Reviews written",
    photosUploaded: "Photos uploaded",
    savedPlaces: "Saved places",
    yourCollection: "Your Collection",
    wishlist: "Wishlist",
    favourites: "Favourites",
    myReviews: "My Reviews",
    myPhotos: "My Photos",
    travelHistory: "Travel History",
    recentReviews: "Recent Reviews",
    noReviewsYet: "You haven't written any reviews yet.",
    youHaveReviews: "You have {count} reviews.",
    locationLabel: "Location",
    itemsSaved: "Items saved",
    reviewsWrittenCount: "Reviews written",
    photosUploadedCount: "Photos uploaded",
    locationPlaceholder: "City or region you explore from",
    bioPlaceholder: "A short introduction shown on your public profile",
    fileTooLarge: "File is too large. Maximum size is 5MB.",
    unsupportedFormat:
      "Unsupported file format. Please upload JPG, PNG, or WEBP.",
    uploadHint: "JPG, PNG or WEBP, max 5MB",
    about: "About this traveller",
    travelActivity: "Travel activity",
    travelActivityComingSoon:
      "More travel activity will appear here in a later update.",
    noPublicBio: "This traveller has not added a public bio yet.",

    // ——— Community / reviews ———
    communityTitle: "Community",
    allReviews: "All reviews",
    latestReviews: "Latest reviews",
    reviewSortNewest: "Newest",
    reviewSortOldest: "Oldest",
    reviewSortHighestRating: "Highest Rating",
    reviewSortLowestRating: "Lowest Rating",
    reviewSortMostLiked: "Most Liked",
    communityFilterLabel: "Filter reviews",
    communityFilterAll: "All Reviews",
    communityFilterWithPhotos: "With Photos",
    communityFilterHighlyRated: "4 Stars & Above",
    communitySearchPlaceholder: "Search review text or attractions",
    communityEmpty: "No community reviews yet.",
    communitySearchEmpty: 'No reviews found for "{query}".',
    communityPhotosEmpty: "No reviews with photos found.",
    communityHighlyRatedEmpty: "No highly rated reviews found.",
    communityClearSearch: "Clear search",
    communityRetry: "Retry",
    communityViewAttraction: "View attraction",
    reviewComment: "Comment",
    reviewComments: "Comments",
    reviewViewComments: "View comments",
    reviewHideComments: "Hide comments",
    reviewWriteComment: "Write a comment",
    reviewCommentPlaceholder: "Share your thoughts...",
    reviewPostComment: "Post comment",
    reviewPostingComment: "Posting...",
    reviewCommentCharacterCount: "{count} / {maximum}",
    reviewCommentsLoading: "Loading comments...",
    reviewNoCommentsYet: "No comments yet",
    reviewBeFirstToComment: "Be the first to comment.",
    reviewViewMoreComments: "View more comments",
    reviewDeleteComment: "Delete comment",
    reviewDeleteCommentConfirm: "Delete this comment?",
    reviewDeletingComment: "Deleting...",
    reviewSignInToComment: "Sign in to comment",
    reviewCommentsRetry: "Retry",
    reviewCommentsLoadFailed: "Failed to load comments.",
    reviewCommentRequired: "Comment text is required.",
    reviewCommentPostFailed: "Failed to post comment.",
    reviewCommentDeleteFailed: "Failed to delete comment.",
    communityPaginationLabel: "Community review pages",
    communityGoToPage: "Go to page {page}",
    selected: "Selected",
    yourRating: "Your rating",
    reviewPlaceholder: "Share your experience...",
    postReview: "Post review",
    editReview: "Edit review",
    deleteReview: "Delete review",
    confirmDeleteReview: "Delete this review?",
    reviewPosted: "Review posted",
    noCommunityReviews: "No reviews yet. Be the first to share.",
    stars: "stars",

    // ——— Map ———
    mapTitle: "Exploration Map",
    mapLoading: "Loading map...",
    mapFailed: "Failed to load map",
    showAll: "Show all",
    visited: "Visited",
    notVisited: "Not visited",
    exploreProgress: "Exploration progress",
    signInForMapFeatures: "Sign in to track places you've visited",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",

    // ——— Travellers / social ———
    travellersTitle: "Travellers",
    searchTravellers: "Search travellers",
    publicProfile: "Public profile",
    noTravellersFound: "No travellers found",
    compareVisits: "Compare visits",
    commonPlaces: "Places in common",
    differentPlaces: "Different places",
    viewProfile: "View profile",

    // ——— Collection pages ———
    wishlistTitle: "Wishlist",
    favouritesTitle: "Favourites",
    myPhotosTitle: "My Photos",
    travelHistoryTitle: "Travel History",
    emptyWishlist: "Your Wishlist is empty",
    emptyFavourites: "No Favourites yet",
    emptyPhotos: "No photos uploaded yet",
    emptyHistory: "No travel history yet",

    // ——— States ———
    state_Johor: "Johor",
    state_Kedah: "Kedah",
    state_Kelantan: "Kelantan",
    state_Melaka: "Melaka",
    state_NegeriSembilan: "Negeri Sembilan",
    state_Pahang: "Pahang",
    state_Penang: "Penang",
    state_Perak: "Perak",
    state_Perlis: "Perlis",
    state_Sabah: "Sabah",
    state_Sarawak: "Sarawak",
    state_Selangor: "Selangor",
    state_Terengganu: "Terengganu",
    state_KualaLumpur: "Kuala Lumpur",
    state_Labuan: "Labuan",
    state_Putrajaya: "Putrajaya",

    editedAt: "Edited {date}",
    readyToEdit: "Ready to edit",
    daysUntilEdit: "Editable in {count} day(s)",

    verifiedVisitBadge: "Verified visit",
    checkingSignIn: "Checking sign-in...",
    signInBeforeVerify: "Sign in before verifying a visit",
    signInBeforeVerifyHint:
      "Sign-in is required before Chatlas asks for location or camera permission.",
    signInStatusUnavailable: "Sign-in status unavailable",
    signInStatusUnavailableHint:
      "Chatlas must confirm your sign-in before requesting location or camera permission. Try the check again or sign in.",
    checkSignInAgain: "Check sign-in again",
    checkingLocation: "Checking your current location...",
    checkingLocationHint:
      "Keep this page open while your device finds a fresh GPS position.",
    choosePlaceVisiting: "Choose the place you are visiting",
    choosePlaceHint:
      "Several supported attractions are nearby. Select one to continue.",
    continueToCamera: "Continue to camera",
    checkingPhotoLimit: "Checking today's photo limit...",
    checkingPhotoLimitHint:
      "The camera will open only when this attraction has an available photo slot.",
    limitFull: "Today's limit is full",
    autoSelected: "Automatically selected: ",
    selectedLabel: "Selected: ",
    openingCamera: "Opening live camera...",
    photoPublicWarning:
      "This photo will be publicly visible. Avoid capturing faces or private information.",
    retake: "Retake",
    capturing: "Capturing...",
    capturePhoto: "Capture Photo",
    uploadingPhoto: "Uploading photo...",
    uploadingPhotoHint:
      "Keep this page open while Chatlas verifies and saves the photo. Closing the page cannot undo an upload the server has already received.",
    uploadPaused: "Upload paused",
    photoStillReady: "Your selected photo is still ready to retry.",
    visitVerified: "Visit verified",
    visitVerifiedHint:
      "Your public photo was saved. Your exploration progress is refreshing.",
    done: "Done",
    verificationPaused: "Verification paused",
    tryAgain: "Try again",
    progressSignIn: "Sign in to view exploration progress",
    progressLoading: "Loading exploration progress...",
    progressLoadFailed: "Unable to load exploration progress",
    progressUnavailable: "Exploration progress unavailable",
    progressHint: "Your verified visits across supported Melaka attractions.",
    noSupportedAttractions: "No supported attractions available",
    progressWhenAvailable:
      "Progress will appear when supported attractions are available.",
    loadingVisited: "Loading visited attractions...",
    visitedConfirmedHint: "Places confirmed by your verified visits.",
    signInViewVisited: "Sign in to view visited attractions",
    visitedDataUnavailable: "Visited data unavailable",
    visitedUnavailableHint:
      "Your visited attractions are not available right now.",
    couldNotLoadVisited: "Could not load visited attractions",
    couldNotLoadVisitedHint:
      "We could not load your visited attractions. Please try again.",
    focusOnMap: "Focus on map",
    viewDetails: "View details",
    mapNotReady: "Available when the interactive map is ready",

    backToTravellers: "Back to travellers",
    publicTravellerProfile: "Public traveller profile",
    locationNotShared: "Location not shared",
    overview: "Overview",
    exploreProgressTab: "Explore progress",
    compare: "Compare",
    publicActivitySummary: "Public activity summary",
    seeActivityTabs: "See activity tabs",
    visitsBasedOnVerified: "Visits and progress are based on verified visits.",

    selectCategory: "Select a category",
    attractionDescriptionPlaceholder: "Short introduction shown on the public listing",
    photosOptional: "optional",
    choosePhoto: "Choose photos",
    noFileChosen: "No file chosen",
    photosSelected: "{count} file(s) selected",
    attractionsCount: "{count} attractions",
    publicTravellerProfile: "Public traveller profile",
    locationNotShared: "Location not shared",
    memberSince: "Member since {date}",
    memberSinceUnavailable: "Member since date unavailable",
    noPublicBio: "This traveller has not added a public bio yet.",
    overview: "Overview",
    exploreProgressTab: "Explore progress",
    compare: "Compare",
    travelActivity: "Travel activity",
    publicActivitySummary: "Public activity summary",
    seeActivityTabs: "See activity tabs",
    reviewsWritten: "Reviews written",
    attractionsVisited: "Attractions visited",
    visitsBasedOnVerified: "Visits and progress are based on verified visits.",
    profileNotFound: "User profile not found",
    profileDoesNotExist: "This public profile does not exist.",
    browseTravellers: "Browse traveller profiles",
    publicReviews: "Public reviews",
    noReviewsAvailable: "No reviews available",
    noReviewsPublished: "This traveller has not published any reviews yet.",
    reviewsUnavailable: "Reviews are not available yet",
    unableLoadReviews: "Unable to load reviews",
    loginToViewProgress: "Log in to view explore progress",
    loginForExploreMaps: "Verified exploration maps are available to registered Chatlas users.",
    loginWithGoogle: "Log in with Google",
    loadingExploreProgress: "Loading explore progress",
    exploreProgressUnavailable: "Explore progress is currently unavailable",
    exploreProgressNotYet: "Explore progress is not available yet",
    noVerifiedVisits: "No verified visits available",
    noVerifiedVisitsHint: "This traveller has not verified a visit to any supported attraction yet.",
    verifiedExplorationMap: "Verified exploration map",
    verifiedAttractionsCount: "{count} verified attraction(s)",
    verifiedLocations: "Verified locations",
    onlyVerifiedShown: "Only verified visits are shown. Precise verification coordinates and photo evidence remain private.",
    loginToCompare: "Log in to compare explored places",
    loginToCompareHint: "Log in with Google to compare your verified exploration with {name}.",
    comparingPlaces: "Comparing explored places",
    comparisonNotYet: "Comparison is not available yet",
    unableCompare: "Unable to compare explored places",
    coverageComparison: "Attraction coverage comparison",
    exploredMaps: "Explored maps",
    exploredMapsHint: "Compare the attractions each traveller has reached through a verified visit. Verification evidence remains private.",
    yourExploredPlaces: "Your explored places",
    theirExploredPlaces: "{name}'s explored places",
    exploredByBoth: "Explored by both travellers",
    onlyExploredByYou: "Only explored by you",
    onlyExploredByThem: "Only explored by {name}",
    you: "You",
    attractionsExplored: "{count} attraction(s) explored",
    exploredCount: "{count} explored",
    noVerifiedOnMap: "No verified attractions to display on this map.",
    noAttractionsInGroup: "No attractions in this group.",
    dateUnavailable: "Date unavailable",
    checkingAccess: "Checking access",
    sectionUnavailable: "This section is currently unavailable.",
    photosShowing: "Photos Showing",
    signInToLike: "Sign in to like",
    like: "Like",
    liked: "Liked",
    updating: "Updating...",
    unlikeReview: "Unlike this review",
    likeReview: "Like this review",
    signInToLikeReview: "Sign in to like this review",
    reviewed: "Reviewed",
    likeSingular: "Like",
    likePlural: "Likes",
    locationAccessDenied: "Location access was denied. Allow location access and try again.",
    verificationPaused: "Verification paused",
    setAsProfile: "Set as Profile",
    showDetails: "Show Details",
    hideDetails: "Hide Details",
    locationAccessDenied: "Location access was denied. Allow location access and try again.",
    locationUnavailable: "Your current location is unavailable. Move to an open area and try again.",
    locationTimeout: "Finding your current location timed out. Try again where you have a clear signal.",
    locationConfirmFailed: "We could not confirm your current location. Please try again.",
    cameraAccessDenied: "Camera access was denied. Allow camera access and try again.",
    cameraNotFound: "A usable camera was not found on this device.",
    cameraInUse: "The camera is unavailable or already in use. Close other camera apps and try again.",
    cameraOpenFailed: "We could not open the camera. Please try again.",
    cameraUnavailableBrowser: "Live camera capture is unavailable in this browser.",
    locationUnavailableBrowser: "Current location is unavailable in this browser.",
    locationValidateFailed: "We could not validate your current location.",
    cameraCaptureFailed: "The camera image could not be captured. Please try again.",
    photoPreviewFailed: "The photo preview could not be created. Please try again.",
    secureUploadFailed: "A secure upload could not be prepared in this browser. Please try again.",
    verifyVisitFailed: "We could not verify this visit. Please try again.",
    sessionExpiredSignIn: "Your session has expired. Sign in and try again.",
    capacityCheckFailed: "We could not check today's photo limit. Please try again.",
    verifiedVisitLimitReached: "You have already verified this attraction today. You can add a new photo on another Malaysia date.",
    uploadPhoto: "Upload Photo",
    mustSignInToReview: "You must be signed in to submit a review.",
    signInViewVisited: "Sign in to view your verified visits",          
    signInViewVisitedHint: "Sign in to see places confirmed by your verified visits",      
    verifiedPhotosLoadError: "Verified Photos Load Error",
    verifiedPhotoDeleteError: "Verified Photo Delete Error",
    signInViewProgress: "Sign in to view exploration progress",
    signInViewProgressHint: "Sign in to track verified visits across supported Melaka attractions.",
  },

  zh: {
    home: "首页",
    attractions: "景点",
    addAttraction: "+ 添加景点",
    browseAttractions: "浏览景点",
    map: "地图",
    travellers: "旅人",
    community: "社区",
    myProfile: "我的资料",
    logout: "登出",
    signIn: "登录",
    menu: "菜单",

    loading: "加载中...",
    cancel: "取消",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    view: "查看",
    back: "返回",
    backToExplore: "返回探索",
    backToProfile: "返回资料",
    search: "搜索",
    reset: "重置",
    submit: "提交",
    close: "关闭",
    yes: "是",
    no: "否",
    remove: "移除",
    errorGeneric: "出错了，请重试。",
    unauthorized: "请先登录。",
    notFound: "页面不存在",

    loginSubtitle: "登录以收藏地点、撰写评价并管理个人资料",
    loginGuestHint: "未登录仍可浏览景点、地图和社区。",
    signInWithGoogle: "使用 Google 登录",
    signingIn: "登录中...",
    continueAsGuest: "以访客身份继续浏览",
    termsAgree: "继续即表示同意服务条款",
    googleAuthFailed: "Google 登录失败，请重试。",

    heroEyebrow: "与社区一起探索马六甲",
    heroTitle: "发现景点，记录你的旅行足迹",
    heroSubtitle:
      "浏览热门与小众景点，阅读旅人分享，开始探索马六甲。",

    searchAttractions: "搜索景点",
    searchPlaceholder: "在马六甲搜索景点",
    moreFilters: "更多筛选",
    hideFilters: "收起筛选",
    minimumRating: "最低评分",
    anyRating: "不限评分",
    ratingAndAbove: "及以上",
    locationArea: "区域",
    allAreas: "全部区域",
    sortBy: "排序方式",
    sortNameAsc: "名称 (A-Z)",
    sortRating: "评分",
    sortNewest: "最新",
    sortOldest: "最旧",
    sortMostReviewed: "评价最多",
    sortLowestRating: "评分最低",
    source: "来源",
    allAttractions: "全部景点",
    communitySubmittedOnly: "仅社区提交",
    allCategories: "全部分类",
    attractionsAvailable: "共 {count} 个景点",
    resultsFound: "找到 {count} 个结果：{criteria}",
    loadingAttractions: "正在加载景点...",
    failedLoadAttractions: "加载景点失败，请重试。",
    noAttractionsFound: "未找到景点",
    tryChangingFilters:
      "请尝试更改关键词、分类、区域、评分，或清除所有筛选。",
    clearSearchAndFilters: "清除搜索与筛选",
    previous: "上一页",
    next: "下一页",
    pageOf: "第 {page} / {total} 页",
    keyword: "关键词",
    category: "分类",
    area: "区域",
    rating: "评分",

    cat_All: "全部分类",
    cat_Museum: "博物馆",
    cat_Religious: "宗教",
    cat_TouristAttraction: "旅游景点",
    cat_Historical: "历史",
    cat_Nature: "自然",
    cat_Entertainment: "娱乐",
    cat_Gallery: "画廊",

    details: "详情",
    address: "地址",
    description: "简介",
    photos: "照片",
    reviews: "评价",
    writeReview: "写评价",
    addToWishlist: "加入心愿单",
    removeFromWishlist: "移出心愿单",
    addToFavourites: "加入收藏",
    removeFromFavourites: "取消收藏",
    signInToSave: "登录以收藏此地",
    signInToReview: "登录以撰写评价",
    editDescription: "编辑简介",
    saveDescription: "保存简介",
    onlyMelakaCanEdit: "仅家在马六甲的用户可编辑简介。",
    uploadPhoto: "上传照片",
    choosePhoto: "选择照片",
    noFileChosen: "未选择文件",
    noPhotosYet: "暂无照片",
    noReviewsYetAttraction: "暂无评价",
    communitySubmitted: "社区提交",
    openInMaps: "在Google地图中打开",
    aboutAttraction: "关于此景点",
    descriptionPlaceholder: "分享这个景点值得一游的原因…",
    noDescription: "此景点暂无简介。",
    sourceWikipedia: "来源：维基百科",
    melakaOnlyFeature: "仅限以马六甲为家的用户",
    addPhoto: "添加照片",
    photoAddedThanks: "照片已添加，感谢贡献！",

    verifiedVisitorPhotos: "已验证访客照片",
    verifiedVisitorPhotosHint:
      "由完成到访验证的旅人分享的现场公开照片。",
    noVerifiedPhotos: "暂无已验证访客照片。",
    verifiedVisit: "已验证到访",
    loadingVerifiedPhotos: "正在加载已验证访客照片...",
    refreshVerifiedPhotos: "正在刷新已验证访客照片...",
    refreshVerifiedFailed:
      "无法加载最新已验证访客照片，下方仍保留当前照片。",
    retryRefresh: "重试刷新",
    signInManageVerified: "登录以管理你的已验证访客照片。",
    signInManageVerifiedHint:
      "照片仍公开显示，但删除需要本人登录会话。",
    reloadPhotos: "重新加载照片",
    deleteVerifiedPhotoConfirm: "删除这张已验证访客照片？此操作无法撤销。",
    deletingPhoto: "正在删除照片...",
    tryDeleteAgain: "再次尝试删除",
    deletePhoto: "删除照片",

    verifyNearbyPlace: "验证附近地点",
    verifyNearbyVisit: "验证附近到访",
    verifyNearbyHint:
      "开始后，Chatlas 会先检查一次当前位置，再打开实时相机，不会持续追踪移动。",
    showLiveLocation: "显示我的实时位置",
    liveLocationHint:
      "开启后，地图仅在本页打开期间显示你的位置；位置只留在本设备，不会储存或上传。",
    explorationProgress: "探索进度",
    visitedAttractions: "已访问景点",
    noVisitedYet: "暂无已访问景点",
    visitedListHint: "通过到访验证确认的景点会出现在此列表。",
    attractionsCount: "{count} 个景点",
    visitedCountLabel: "{count} 已访问",
    ofAttractionsVisited: "已访问 {visited} / {total} 个景点",
    newExplorer: "新晋探索者",
    personalExploration: "个人探索",

    addAttractionTitle: "添加景点",
    attractionName: "名称",
    attractionCategory: "分类",
    attractionAddress: "地址",
    attractionDescriptionOptional: "简介（可选）",
    submitAttraction: "提交景点",
    submitSuccess: "景点提交成功",
    submitFailed: "提交失败",
    signInToAddAttraction: "登录以添加景点",

    editProfile: "编辑资料",
    displayName: "显示名称",
    email: "邮箱",
    location: "所在地",
    homeState: "所在州属",
    selectStateTerritory: "选择州属 / 联邦直辖区",
    locationLegacyHint:
      "原值「{value}」不在列表中，请重新选择州属。",
    melakaEditHint: "你可以编辑马六甲景点的简介。",
    bio: "简介",
    saveChanges: "保存修改",
    saving: "保存中...",
    profileUpdated: "资料更新成功！",
    placesVisited: "已访问地点",
    reviewsWritten: "已写评价",
    photosUploaded: "已上传照片",
    savedPlaces: "已收藏地点",
    yourCollection: "我的收藏",
    wishlist: "心愿单",
    favourites: "收藏",
    myReviews: "我的评价",
    myPhotos: "我的照片",
    travelHistory: "旅行历史",
    recentReviews: "最近评价",
    noReviewsYet: "你还没有写过任何评价。",
    youHaveReviews: "你有 {count} 条评价。",
    locationLabel: "所在地",
    itemsSaved: "项已保存",
    reviewsWrittenCount: "条评价",
    photosUploadedCount: "张照片",
    locationPlaceholder: "你常探索的城市或地区",
    bioPlaceholder: "展示在公开资料上的简短介绍",
    fileTooLarge: "文件过大，最大 5MB。",
    unsupportedFormat: "不支持的格式，请上传 JPG、PNG 或 WEBP。",
    uploadHint: "JPG、PNG 或 WEBP，最大 5MB",
    about: "关于这位旅人",
    travelActivity: "旅行动态",
    travelActivityComingSoon: "更多旅行动态将在后续更新中显示。",
    noPublicBio: "这位旅人尚未添加公开简介。",

    communityTitle: "社区",
    allReviews: "全部评价",
    latestReviews: "最新评价",
    reviewSortNewest: "最新",
    reviewSortOldest: "最早",
    reviewSortHighestRating: "评分最高",
    reviewSortLowestRating: "评分最低",
    reviewSortMostLiked: "最多赞",
    communityFilterLabel: "筛选评价",
    communityFilterAll: "全部评价",
    communityFilterWithPhotos: "含照片",
    communityFilterHighlyRated: "4 星及以上",
    communitySearchPlaceholder: "搜索评价内容或景点",
    communityEmpty: "暂无社区评价。",
    communitySearchEmpty: "未找到有关“{query}”的评价。",
    communityPhotosEmpty: "未找到含照片的评价。",
    communityHighlyRatedEmpty: "未找到高评分评价。",
    communityClearSearch: "清除搜索",
    communityRetry: "重试",
    communityViewAttraction: "查看景点",
    reviewComment: "评论",
    reviewComments: "评论",
    reviewViewComments: "查看评论",
    reviewHideComments: "隐藏评论",
    reviewWriteComment: "写评论",
    reviewCommentPlaceholder: "分享您的想法…",
    reviewPostComment: "发表评论",
    reviewPostingComment: "发布中…",
    reviewCommentCharacterCount: "{count} / {maximum}",
    reviewCommentsLoading: "正在加载评论…",
    reviewNoCommentsYet: "暂无评论",
    reviewBeFirstToComment: "成为第一个评论的人。",
    reviewViewMoreComments: "查看更多评论",
    reviewDeleteComment: "删除评论",
    reviewDeleteCommentConfirm: "确定要删除这条评论吗？",
    reviewDeletingComment: "删除中…",
    reviewSignInToComment: "登录后评论",
    reviewCommentsRetry: "重试",
    reviewCommentsLoadFailed: "无法加载评论。",
    reviewCommentRequired: "评论内容为必填项。",
    reviewCommentPostFailed: "无法发表评论。",
    reviewCommentDeleteFailed: "无法删除评论。",
    communityPaginationLabel: "社区评价分页",
    communityGoToPage: "前往第 {page} 页",
    selected: "已选择",
    yourRating: "你的评分",
    reviewPlaceholder: "分享你的体验...",
    postReview: "发布评价",
    editReview: "编辑评价",
    deleteReview: "删除评价",
    confirmDeleteReview: "确定删除这条评价？",
    reviewPosted: "评价已发布",
    noCommunityReviews: "还没有评价，来当第一个分享的人吧。",
    stars: "星",

    mapTitle: "探索地图",
    mapLoading: "地图加载中...",
    mapFailed: "地图加载失败",
    showAll: "显示全部",
    visited: "已去过",
    notVisited: "未去过",
    exploreProgress: "探索进度",
    signInForMapFeatures: "登录以记录去过的地点",
    zoomIn: "放大",
    zoomOut: "缩小",

    travellersTitle: "旅人",
    searchTravellers: "搜索旅人",
    publicProfile: "公开资料",
    noTravellersFound: "未找到旅人",
    compareVisits: "对比足迹",
    commonPlaces: "共同去过",
    differentPlaces: "不同足迹",
    viewProfile: "查看资料",

    wishlistTitle: "心愿单",
    favouritesTitle: "收藏",
    myPhotosTitle: "我的照片",
    travelHistoryTitle: "旅行历史",
    emptyWishlist: "心愿单是空的",
    emptyFavourites: "暂无收藏",
    emptyPhotos: "尚未上传照片",
    emptyHistory: "暂无旅行记录",

    state_Johor: "柔佛",
    state_Kedah: "吉打",
    state_Kelantan: "吉兰丹",
    state_Melaka: "马六甲",
    state_NegeriSembilan: "森美兰",
    state_Pahang: "彭亨",
    state_Penang: "槟城",
    state_Perak: "霹雳",
    state_Perlis: "玻璃市",
    state_Sabah: "沙巴",
    state_Sarawak: "砂拉越",
    state_Selangor: "雪兰莪",
    state_Terengganu: "登嘉楼",
    state_KualaLumpur: "吉隆坡",
    state_Labuan: "纳闽",
    state_Putrajaya: "布城",
    
    editedAt: "编辑于 {date}",
    readyToEdit: "可编辑",
    daysUntilEdit: "{count} 天后可编辑",

    verifiedVisitBadge: "已验证到访",
    checkingSignIn: "正在确认登录...",
    signInBeforeVerify: "验证到访前请先登录",
    signInBeforeVerifyHint:
      "在请求位置或相机权限前，Chatlas 需要你已登录。",
    signInStatusUnavailable: "无法确认登录状态",
    signInStatusUnavailableHint:
      "请求位置或相机前必须确认登录。请重试或登录。",
    checkSignInAgain: "再次检查登录",
    checkingLocation: "正在获取当前位置...",
    checkingLocationHint: "请保持页面打开，等待设备定位。",
    choosePlaceVisiting: "选择你正在访问的地点",
    choosePlaceHint: "附近有多个支持的景点，请选择一个继续。",
    continueToCamera: "继续打开相机",
    checkingPhotoLimit: "正在检查今日照片限额...",
    checkingPhotoLimitHint: "仅在有可用名额时才会打开相机。",
    limitFull: "今日名额已满",
    autoSelected: "已自动选择：",
    selectedLabel: "已选择：",
    openingCamera: "正在打开实时相机...",
    photoPublicWarning: "此照片将公开显示。请避免拍摄人脸或私人信息。",
    retake: "重拍",
    capturing: "拍摄中...",
    capturePhoto: "拍摄照片",
    uploadingPhoto: "正在上传照片...",
    uploadingPhotoHint:
      "上传期间请保持页面打开。服务器已收到的上传无法通过关闭页面撤销。",
    uploadPaused: "上传已暂停",
    photoStillReady: "当前照片仍可重试上传。",
    visitVerified: "到访已验证",
    visitVerifiedHint: "公开照片已保存，探索进度正在刷新。",
    done: "完成",
    verificationPaused: "验证已暂停",
    tryAgain: "重试",
    progressSignIn: "登录以查看探索进度",
    progressLoading: "正在加载探索进度...",
    progressLoadFailed: "无法加载探索进度",
    progressUnavailable: "探索进度不可用",
    progressHint: "你在受支持马六甲景点的已验证到访。",
    noSupportedAttractions: "暂无可用受支持景点",
    progressWhenAvailable: "有受支持景点后将显示进度。",
    loadingVisited: "正在加载已访问景点...",
    visitedConfirmedHint: "由你的已验证到访确认的地点。",
    signInViewVisited: "登录以查看已访问景点",
    visitedDataUnavailable: "已访问数据不可用",
    visitedUnavailableHint: "暂时无法显示已访问景点。",
    couldNotLoadVisited: "无法加载已访问景点",
    couldNotLoadVisitedHint: "加载失败，请重试。",
    focusOnMap: "在地图上定位",
    viewDetails: "查看详情",
    mapNotReady: "交互地图就绪后可用",

    selectCategory: "选择分类",
    attractionDescriptionPlaceholder: "展示在公开资料上的简短介绍",
    photosOptional: "可选",
    choosePhoto: "选择照片",
    noFileChosen: "未选择文件",
    photosSelected: "已选 {count} 个文件",
    attractionsCount: "{count} 个景点",
    backToTravellers: "返回旅人列表",
    publicTravellerProfile: "公开旅人资料",
    locationNotShared: "未分享所在地",
    memberSince: "加入于 {date}",
    memberSinceUnavailable: "加入日期不可用",
    noPublicBio: "这位旅人尚未填写公开简介。",
    overview: "概览",
    exploreProgressTab: "探索进度",
    compare: "对比",
    travelActivity: "旅行动态",
    publicActivitySummary: "公开活动摘要",
    seeActivityTabs: "查看活动标签",
    reviewsWritten: "已写评价",
    attractionsVisited: "已访景点",
    visitsBasedOnVerified: "访问与进度基于已验证的到访。",
    profileNotFound: "未找到用户资料",
    profileDoesNotExist: "此公开资料不存在。",
    browseTravellers: "浏览旅人资料",
    publicReviews: "公开评价",
    noReviewsAvailable: "暂无评价",
    noReviewsPublished: "这位旅人尚未发布任何评价。",
    reviewsUnavailable: "评价功能暂不可用",
    unableLoadReviews: "无法加载评价",
    loginToViewProgress: "登录后查看探索进度",
    loginForExploreMaps: "已验证的探索地图仅对已注册 Chatlas 用户开放。",
    loginWithGoogle: "使用 Google 登录",
    loadingExploreProgress: "正在加载探索进度",
    exploreProgressUnavailable: "探索进度暂时不可用",
    exploreProgressNotYet: "探索进度尚未开放",
    noVerifiedVisits: "暂无已验证到访",
    noVerifiedVisitsHint: "这位旅人尚未对任何支持的景点完成到访验证。",
    verifiedExplorationMap: "已验证探索地图",
    verifiedAttractionsCount: "{count} 个已验证景点",
    verifiedLocations: "已验证地点",
    onlyVerifiedShown: "仅显示已验证到访。精确验证坐标与照片证据保持私密。",
    loginToCompare: "登录后对比探索地点",
    loginToCompareHint: "使用 Google 登录，与 {name} 对比已验证的探索。",
    comparingPlaces: "正在对比探索地点",
    comparisonNotYet: "对比功能尚未开放",
    unableCompare: "无法对比探索地点",
    coverageComparison: "景点覆盖对比",
    exploredMaps: "探索地图",
    exploredMapsHint: "对比各位旅人通过已验证到访到达的景点。验证证据保持私密。",
    yourExploredPlaces: "你探索过的地点",
    theirExploredPlaces: "{name} 探索过的地点",
    exploredByBoth: "双方都探索过",
    onlyExploredByYou: "仅你探索过",
    onlyExploredByThem: "仅 {name} 探索过",
    you: "你",
    attractionsExplored: "已探索 {count} 个景点",
    exploredCount: "已探索 {count} 处",
    noVerifiedOnMap: "此地图上暂无可显示的已验证景点。",
    noAttractionsInGroup: "此分组暂无景点。",
    dateUnavailable: "日期不可用",
    checkingAccess: "正在检查访问权限",
    sectionUnavailable: "此区块暂时不可用。",
    photosShowing: "照片展示",
    signInToLike: "登录后点赞",
    like: "点赞",
    liked: "已赞",
    updating: "更新中...",
    unlikeReview: "取消点赞",
    likeReview: "点赞这条评价",
    signInToLikeReview: "登录后可为评价点赞",
    reviewed: "评价了",
    likeSingular: "赞",
    likePlural: "赞",
    locationAccessDenied: "定位权限被拒绝。请允许位置访问后重试。",
    verificationPaused: "验证已暂停",
    setAsProfile: "设为头像",
    showDetails: "显示详情",
    hideDetails: "隐藏详情",
    locationAccessDenied: "位置访问权限被拒绝。请允许访问位置信息并重试。",
    locationUnavailable: "无法获取您当前的位置。请移步至开阔地带，然后重试。",
    locationTimeout: "获取当前位置时超时。请在信号良好的地方重试。",
    locationConfirmFailed: "我们无法确认您当前的位置。请重试。",
    cameraAccessDenied: "无法访问摄像头。请允许访问摄像头并重试。",
    cameraNotFound: "未在此设备上找到可用的摄像头。",
    cameraInUse: "摄像头不可用或已被占用。请关闭其他摄像头应用，然后重试。",
    cameraOpenFailed: "无法打开摄像头。请重试。",
    cameraUnavailableBrowser: "此浏览器不支持实时摄像头拍摄。",
    locationUnavailableBrowser: "此浏览器无法获取当前位置。",
    locationValidateFailed: "我们无法验证您当前的地理位置。",
    cameraCaptureFailed: "无法获取摄像机图像。请重试。",
    photoPreviewFailed: "无法生成照片预览。请重试。",
    secureUploadFailed: "无法在此浏览器中准备安全上传。请重试。",
    verifyVisitFailed: "我们无法验证此次访问。请重试。",
    sessionExpiredSignIn: "您的会话已过期。请登录后重试。",
    capacityCheckFailed: "无法查询今日的照片限额。请重试。",
    verifiedVisitLimitReached: "您今天已经验证过该景点了。您可以在马来西亚的其他日期添加新照片。",
    uploadPhoto: "上传照片",
    mustSignInToReview: "您必须登录才能提交评论。",
    signInViewVisited: "登录以查看您已验证的访问记录",          
    signInViewVisitedHint: "登录以查看经您核实造访所确认的地点",      
    verifiedPhotosLoadError: "已验证照片加载错误",
    verifiedPhotoDeleteError: "已验证照片删除错误",
    signInViewProgress: "登录以查看探索进度",
    signInViewProgressHint: "登录以追踪在马六甲指定景点进行的已验证访问。",
  },

  ms: {
    home: "Laman Utama",
    attractions: "Tarikan",
    addAttraction: "+ Tambah Tarikan",
    browseAttractions: "Lihat Tarikan",
    map: "Peta",
    travellers: "Pengembara",
    community: "Komuniti",
    myProfile: "Profil Saya",
    logout: "Log Keluar",
    signIn: "Log Masuk",
    menu: "Menu",

    loading: "Memuatkan...",
    cancel: "Batal",
    save: "Simpan",
    delete: "Padam",
    edit: "Edit",
    view: "Lihat",
    back: "Kembali",
    backToExplore: "Kembali ke Penerokaan",
    backToProfile: "Kembali ke Profil",
    search: "Cari",
    reset: "Set Semula",
    submit: "Hantar",
    close: "Tutup",
    yes: "Ya",
    no: "Tidak",
    remove: "Buang",
    errorGeneric: "Berlaku ralat. Sila cuba lagi.",
    unauthorized: "Sila log masuk untuk teruskan.",
    notFound: "Halaman tidak dijumpai",

    loginSubtitle:
      "Log masuk untuk simpan tempat, tulis ulasan dan urus profil",
    loginGuestHint:
      "Anda masih boleh layari tarikan, peta dan komuniti sebagai tetamu.",
    signInWithGoogle: "Log masuk dengan Google",
    signingIn: "Sedang log masuk...",
    continueAsGuest: "Teruskan melayari sebagai tetamu",
    termsAgree:
      "Dengan meneruskan, anda bersetuju dengan Terma Perkhidmatan kami",
    googleAuthFailed: "Pengesahan Google gagal. Sila cuba lagi.",

    heroEyebrow: "Terokai Melaka bersama komuniti",
    heroTitle: "Temui tarikan dan rekod perjalanan anda",
    heroSubtitle:
      "Layari tarikan popular dan tersembunyi, baca pengalaman pengembara dan mula terokai Melaka.",

    searchAttractions: "Cari Tarikan",
    searchPlaceholder: "Cari tarikan di Melaka",
    moreFilters: "Lagi Penapis",
    hideFilters: "Sembunyikan Penapis",
    minimumRating: "Penilaian Minimum",
    anyRating: "Sebarang Penilaian",
    ratingAndAbove: "dan ke atas",
    locationArea: "Kawasan",
    allAreas: "Semua Kawasan",
    sortBy: "Susun mengikut",
    sortNameAsc: "Nama (A-Z)",
    sortRating: "Penilaian",
    sortNewest: "Terbaharu",
    sortOldest: "Terlama",
    sortMostReviewed: "Paling Banyak Diulas",
    sortLowestRating: "Penilaian Terendah",
    source: "Sumber",
    allAttractions: "Semua Tarikan",
    communitySubmittedOnly: "Hanya diserahkan komuniti",
    allCategories: "Semua Kategori",
    attractionsAvailable: "{count} tarikan tersedia",
    resultsFound: "{count} keputusan dijumpai untuk {criteria}",
    loadingAttractions: "Memuatkan tarikan...",
    failedLoadAttractions: "Gagal memuatkan tarikan. Sila cuba lagi.",
    noAttractionsFound: "Tiada tarikan dijumpai",
    tryChangingFilters:
      "Cuba ubah kata kunci, kategori, kawasan, penilaian, atau kosongkan semua penapis.",
    clearSearchAndFilters: "Kosongkan Carian dan Penapis",
    previous: "Sebelum",
    next: "Seterusnya",
    pageOf: "Halaman {page} daripada {total}",
    keyword: "kata kunci",
    category: "kategori",
    area: "kawasan",
    rating: "penilaian",

    cat_All: "Semua Kategori",
    cat_Museum: "Muzium",
    cat_Religious: "Agama",
    cat_TouristAttraction: "Tarikan Pelancong",
    cat_Historical: "Sejarah",
    cat_Nature: "Alam",
    cat_Entertainment: "Hiburan",
    cat_Gallery: "Galeri",

    details: "Butiran",
    address: "Alamat",
    description: "Penerangan",
    photos: "Foto",
    reviews: "Ulasan",
    writeReview: "Tulis ulasan",
    addToWishlist: "Tambah ke senarai hajat",
    removeFromWishlist: "Buang dari senarai hajat",
    addToFavourites: "Tambah ke kegemaran",
    removeFromFavourites: "Buang dari kegemaran",
    signInToSave: "Log masuk untuk simpan tempat ini",
    signInToReview: "Log masuk untuk tulis ulasan",
    editDescription: "Edit penerangan",
    saveDescription: "Simpan penerangan",
    onlyMelakaCanEdit:
      "Hanya pengguna yang negeri asal Melaka boleh edit penerangan.",
    uploadPhoto: "Muat naik foto",
    choosePhoto: "Pilih foto",
    noFileChosen: "Tiada fail dipilih",
    noPhotosYet: "Tiada foto lagi",
    noReviewsYetAttraction: "Tiada ulasan lagi",
    communitySubmitted: "Diserahkan komuniti",
    // TODO: Confirm this Bahasa Melayu wording with a native speaker.
    openInMaps: "Buka dalam Google Maps",
    aboutAttraction: "Mengenai tarikan ini",
    descriptionPlaceholder:
      "Kongsi mengapa tarikan ini berbaloi dilawati…",
    noDescription: "Tiada penerangan untuk tarikan ini lagi.",
    sourceWikipedia: "Sumber: Wikipedia",
    melakaOnlyFeature: "Untuk pengguna berpangkalan di Melaka",
    addPhoto: "Tambah foto",
    photoAddedThanks: "Foto ditambah — terima kasih!",

    verifiedVisitorPhotos: "Foto Pelawat Disahkan",
    verifiedVisitorPhotosHint:
      "Foto awam di lokasi yang dikongsi pengembara yang mengesahkan lawatan.",
    noVerifiedPhotos: "Tiada foto pelawat disahkan lagi.",
    verifiedVisit: "Lawatan Disahkan",
    loadingVerifiedPhotos: "Memuatkan foto pelawat disahkan...",
    refreshVerifiedPhotos: "Menyegar foto pelawat disahkan...",
    refreshVerifiedFailed:
      "Foto pelawat disahkan terkini tidak dapat dimuatkan. Foto semasa dikekalkan di bawah.",
    retryRefresh: "Cuba semula",
    signInManageVerified:
      "Log masuk untuk urus foto pelawat disahkan anda.",
    signInManageVerifiedHint:
      "Foto kekal awam, tetapi pemadaman memerlukan sesi pemilik yang log masuk.",
    reloadPhotos: "Muat semula foto",
    deleteVerifiedPhotoConfirm:
      "Padam foto pelawat disahkan ini? Tindakan ini tidak boleh dibuat asal.",
    deletingPhoto: "Memadam foto...",
    tryDeleteAgain: "Cuba padam semula",
    deletePhoto: "Padam foto",

    verifyNearbyPlace: "Sahkan tempat berdekatan",
    verifyNearbyVisit: "Sahkan lawatan berdekatan",
    verifyNearbyHint:
      "Apabila bermula, Chatlas menyemak lokasi semasa sekali kemudian membuka kamera. Ia tidak menjejak pergerakan.",
    showLiveLocation: "Tunjuk lokasi langsung saya",
    liveLocationHint:
      "Apabila diaktifkan, peta menunjukkan lokasi anda semasa halaman ini dibuka. Lokasi kekal pada peranti ini.",
    explorationProgress: "Kemajuan penerokaan",
    visitedAttractions: "Tarikan dilawati",
    noVisitedYet: "Tiada tarikan dilawati lagi",
    visitedListHint:
      "Tarikan yang disahkan melalui lawatan akan dipaparkan di sini.",
    attractionsCount: "{count} tarikan",
    visitedCountLabel: "{count} dilawati",
    ofAttractionsVisited: "{visited} daripada {total} tarikan dilawati",
    newExplorer: "Peneroka baharu",
    personalExploration: "Penerokaan peribadi",

    addAttractionTitle: "Tambah Tarikan",
    attractionName: "Nama",
    attractionCategory: "Kategori",
    attractionAddress: "Alamat",
    attractionDescriptionOptional: "Penerangan (pilihan)",
    submitAttraction: "Hantar tarikan",
    submitSuccess: "Tarikan berjaya dihantar",
    submitFailed: "Gagal menghantar tarikan",
    signInToAddAttraction: "Log masuk untuk tambah tarikan",

    editProfile: "Edit Profil",
    displayName: "Nama paparan",
    email: "E-mel",
    location: "Lokasi",
    homeState: "Negeri asal",
    selectStateTerritory: "Pilih negeri / wilayah persekutuan",
    locationLegacyHint:
      'Nilai lama "{value}" tiada dalam senarai. Sila pilih negeri di atas.',
    melakaEditHint: "Anda boleh edit penerangan tarikan Melaka.",
    bio: "Bio",
    saveChanges: "Simpan perubahan",
    saving: "Menyimpan...",
    profileUpdated: "Profil berjaya dikemas kini!",
    placesVisited: "Tempat dilawati",
    reviewsWritten: "Ulasan ditulis",
    photosUploaded: "Foto dimuat naik",
    savedPlaces: "Tempat disimpan",
    yourCollection: "Koleksi Anda",
    wishlist: "Senarai Hajat",
    favourites: "Kegemaran",
    myReviews: "Ulasan Saya",
    myPhotos: "Foto Saya",
    travelHistory: "Sejarah Perjalanan",
    recentReviews: "Ulasan Terkini",
    noReviewsYet: "Anda belum menulis sebarang ulasan.",
    youHaveReviews: "Anda mempunyai {count} ulasan.",
    locationLabel: "Lokasi",
    itemsSaved: "item disimpan",
    reviewsWrittenCount: "ulasan ditulis",
    photosUploadedCount: "foto dimuat naik",
    locationPlaceholder: "Bandar atau kawasan yang anda terokai",
    bioPlaceholder: "Pengenalan ringkas pada profil awam anda",
    fileTooLarge: "Fail terlalu besar. Maksimum 5MB.",
    unsupportedFormat:
      "Format tidak disokong. Sila muat naik JPG, PNG, atau WEBP.",
    uploadHint: "JPG, PNG atau WEBP, maks 5MB",
    about: "Mengenai pengembara ini",
    travelActivity: "Aktiviti perjalanan",
    travelActivityComingSoon:
      "Lebih banyak aktiviti perjalanan akan dipaparkan kemudian.",
    noPublicBio: "Pengembara ini belum menambah bio awam.",

    communityTitle: "Komuniti",
    allReviews: "Semua ulasan",
    latestReviews: "Ulasan terkini",
    reviewSortNewest: "Terbaharu",
    reviewSortOldest: "Terlama",
    reviewSortHighestRating: "Penilaian Tertinggi",
    reviewSortLowestRating: "Penilaian Terendah",
    reviewSortMostLiked: "Paling Disukai",
    communityFilterLabel: "Tapis ulasan",
    communityFilterAll: "Semua Ulasan",
    communityFilterWithPhotos: "Dengan Foto",
    communityFilterHighlyRated: "4 Bintang & Ke Atas",
    communitySearchPlaceholder: "Cari teks ulasan atau tarikan",
    communityEmpty: "Belum ada ulasan komuniti.",
    communitySearchEmpty: 'Tiada ulasan dijumpai untuk "{query}".',
    communityPhotosEmpty: "Tiada ulasan dengan foto dijumpai.",
    communityHighlyRatedEmpty: "Tiada ulasan berpenilaian tinggi dijumpai.",
    communityClearSearch: "Kosongkan carian",
    communityRetry: "Cuba lagi",
    communityViewAttraction: "Lihat tarikan",
    reviewComment: "Komen",
    reviewComments: "Komen",
    reviewViewComments: "Lihat komen",
    reviewHideComments: "Sembunyikan komen",
    reviewWriteComment: "Tulis komen",
    reviewCommentPlaceholder: "Kongsi pendapat anda…",
    reviewPostComment: "Hantar komen",
    reviewPostingComment: "Sedang menghantar…",
    reviewCommentCharacterCount: "{count} / {maximum}",
    reviewCommentsLoading: "Memuatkan komen…",
    reviewNoCommentsYet: "Belum ada komen",
    reviewBeFirstToComment: "Jadilah orang pertama yang memberi komen.",
    reviewViewMoreComments: "Lihat lebih banyak komen",
    reviewDeleteComment: "Padam komen",
    reviewDeleteCommentConfirm: "Padam komen ini?",
    reviewDeletingComment: "Sedang memadam…",
    reviewSignInToComment: "Log masuk untuk memberi komen",
    reviewCommentsRetry: "Cuba lagi",
    reviewCommentsLoadFailed: "Gagal memuatkan komen.",
    reviewCommentRequired: "Teks komen diperlukan.",
    reviewCommentPostFailed: "Gagal menghantar komen.",
    reviewCommentDeleteFailed: "Gagal memadam komen.",
    communityPaginationLabel: "Halaman ulasan komuniti",
    communityGoToPage: "Pergi ke halaman {page}",
    selected: "Dipilih",
    yourRating: "Penilaian anda",
    reviewPlaceholder: "Kongsi pengalaman anda...",
    postReview: "Siarkan ulasan",
    editReview: "Edit ulasan",
    deleteReview: "Padam ulasan",
    confirmDeleteReview: "Padam ulasan ini?",
    reviewPosted: "Ulasan disiar",
    noCommunityReviews: "Tiada ulasan lagi. Jadilah yang pertama.",
    stars: "bintang",

    mapTitle: "Peta Penerokaan",
    mapLoading: "Memuatkan peta...",
    mapFailed: "Gagal memuatkan peta",
    showAll: "Papar semua",
    visited: "Dilawati",
    notVisited: "Belum dilawati",
    exploreProgress: "Kemajuan penerokaan",
    signInForMapFeatures: "Log masuk untuk jejak tempat dilawati",
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",

    travellersTitle: "Pengembara",
    searchTravellers: "Cari pengembara",
    publicProfile: "Profil awam",
    noTravellersFound: "Tiada pengembara dijumpai",
    compareVisits: "Banding lawatan",
    commonPlaces: "Tempat sama",
    differentPlaces: "Tempat berbeza",
    viewProfile: "Lihat profil",

    wishlistTitle: "Senarai Hajat",
    favouritesTitle: "Kegemaran",
    myPhotosTitle: "Foto Saya",
    travelHistoryTitle: "Sejarah Perjalanan",
    emptyWishlist: "Senarai hajat kosong",
    emptyFavourites: "Tiada kegemaran lagi",
    emptyPhotos: "Belum muat naik foto",
    emptyHistory: "Tiada sejarah perjalanan",

    state_Johor: "Johor",
    state_Kedah: "Kedah",
    state_Kelantan: "Kelantan",
    state_Melaka: "Melaka",
    state_NegeriSembilan: "Negeri Sembilan",
    state_Pahang: "Pahang",
    state_Penang: "Pulau Pinang",
    state_Perak: "Perak",
    state_Perlis: "Perlis",
    state_Sabah: "Sabah",
    state_Sarawak: "Sarawak",
    state_Selangor: "Selangor",
    state_Terengganu: "Terengganu",
    state_KualaLumpur: "Kuala Lumpur",
    state_Labuan: "Labuan",
    state_Putrajaya: "Putrajaya",

    editedAt: "Diedit {date}",
    readyToEdit: "Boleh diedit",
    daysUntilEdit: "Boleh diedit dalam {count} hari",

    verifiedVisitBadge: "Lawatan disahkan",
    checkingSignIn: "Menyemak log masuk...",
    signInBeforeVerify: "Log masuk sebelum sahkan lawatan",
    signInBeforeVerifyHint:
      "Log masuk diperlukan sebelum Chatlas meminta kebenaran lokasi atau kamera.",
    signInStatusUnavailable: "Status log masuk tidak tersedia",
    signInStatusUnavailableHint:
      "Chatlas mesti sahkan log masuk sebelum meminta lokasi atau kamera. Cuba semula atau log masuk.",
    checkSignInAgain: "Semak log masuk semula",
    checkingLocation: "Menyemak lokasi semasa...",
    checkingLocationHint:
      "Biarkan halaman ini dibuka sementara peranti mencari kedudukan GPS.",
    choosePlaceVisiting: "Pilih tempat yang anda lawati",
    choosePlaceHint:
      "Beberapa tarikan disokong berdekatan. Pilih satu untuk teruskan.",
    continueToCamera: "Teruskan ke kamera",
    checkingPhotoLimit: "Menyemak had foto hari ini...",
    checkingPhotoLimitHint:
      "Kamera dibuka hanya jika tarikan ini mempunyai slot foto.",
    limitFull: "Had hari ini penuh",
    autoSelected: "Dipilih secara automatik: ",
    selectedLabel: "Dipilih: ",
    openingCamera: "Membuka kamera langsung...",
    photoPublicWarning:
      "Foto ini akan dipaparkan secara awam. Elakkan wajah atau maklumat peribadi.",
    retake: "Ambil semula",
    capturing: "Sedang menangkap...",
    capturePhoto: "Tangkap foto",
    uploadingPhoto: "Memuat naik foto...",
    uploadingPhotoHint:
      "Biarkan halaman dibuka semasa Chatlas mengesahkan dan menyimpan foto.",
    uploadPaused: "Muat naik dijeda",
    photoStillReady: "Foto terpilih masih sedia untuk cuba semula.",
    visitVerified: "Lawatan disahkan",
    visitVerifiedHint:
      "Foto awam disimpan. Kemajuan penerokaan sedang dimuat semula.",
    done: "Selesai",
    verificationPaused: "Pengesahan dijeda",
    tryAgain: "Cuba lagi",
    progressSignIn: "Log masuk untuk lihat kemajuan penerokaan",
    progressLoading: "Memuatkan kemajuan penerokaan...",
    progressLoadFailed: "Tidak dapat memuatkan kemajuan penerokaan",
    progressUnavailable: "Kemajuan penerokaan tidak tersedia",
    progressHint: "Lawatan disahkan anda merentas tarikan Melaka yang disokong.",
    noSupportedAttractions: "Tiada tarikan disokong tersedia",
    progressWhenAvailable:
      "Kemajuan akan dipaparkan apabila tarikan disokong tersedia.",
    loadingVisited: "Memuatkan tarikan dilawati...",
    visitedConfirmedHint: "Tempat yang disahkan oleh lawatan anda.",
    signInViewVisited: "Log masuk untuk lihat tarikan dilawati",
    visitedDataUnavailable: "Data dilawati tidak tersedia",
    visitedUnavailableHint: "Tarikan dilawati tidak tersedia buat masa ini.",
    couldNotLoadVisited: "Tidak dapat memuatkan tarikan dilawati",
    couldNotLoadVisitedHint:
      "Kami tidak dapat memuatkan tarikan dilawati. Sila cuba lagi.",
    focusOnMap: "Fokus pada peta",
    viewDetails: "Lihat butiran",
    mapNotReady: "Tersedia apabila peta interaktif sedia",
    edit: "Sunting",

    selectCategory: "Pilih kategori",
    attractionDescriptionPlaceholder: "Pengenalan ringkas pada senarai awam",
    photosOptional: "pilihan",
    choosePhoto: "Pilih foto",
    noFileChosen: "Tiada fail dipilih",
    photosSelected: "{count} fail dipilih",
    attractionsCount: "{count} tarikan",
    backToTravellers: "Kembali ke pengembara",
    publicTravellerProfile: "Profil pengembara awam",
    locationNotShared: "Lokasi tidak dikongsi",
    memberSince: "Ahli sejak {date}",
    memberSinceUnavailable: "Tarikh ahli tidak tersedia",
    noPublicBio: "Pengembara ini belum menambah bio awam.",
    overview: "Gambaran keseluruhan",
    exploreProgressTab: "Kemajuan penerokaan",
    compare: "Banding",
    travelActivity: "Aktiviti perjalanan",
    publicActivitySummary: "Ringkasan aktiviti awam",
    seeActivityTabs: "Lihat tab aktiviti",
    reviewsWritten: "Ulasan ditulis",
    attractionsVisited: "Tarikan dilawati",
    visitsBasedOnVerified: "Lawatan dan kemajuan berdasarkan lawatan disahkan.",
    profileNotFound: "Profil pengguna tidak dijumpai",
    profileDoesNotExist: "Profil awam ini tidak wujud.",
    browseTravellers: "Semak profil pengembara",
    publicReviews: "Ulasan awam",
    noReviewsAvailable: "Tiada ulasan",
    noReviewsPublished: "Pengembara ini belum menerbitkan sebarang ulasan.",
    reviewsUnavailable: "Ulasan belum tersedia",
    unableLoadReviews: "Tidak dapat memuatkan ulasan",
    loginToViewProgress: "Log masuk untuk melihat kemajuan penerokaan",
    loginForExploreMaps: "Peta penerokaan disahkan tersedia untuk pengguna Chatlas berdaftar.",
    loginWithGoogle: "Log masuk dengan Google",
    loadingExploreProgress: "Memuatkan kemajuan penerokaan",
    exploreProgressUnavailable: "Kemajuan penerokaan tidak tersedia buat masa ini",
    exploreProgressNotYet: "Kemajuan penerokaan belum tersedia",
    noVerifiedVisits: "Tiada lawatan disahkan",
    noVerifiedVisitsHint: "Pengembara ini belum mengesahkan lawatan ke mana-mana tarikan yang disokong.",
    verifiedExplorationMap: "Peta penerokaan disahkan",
    verifiedAttractionsCount: "{count} tarikan disahkan",
    verifiedLocations: "Lokasi disahkan",
    onlyVerifiedShown: "Hanya lawatan disahkan dipaparkan. Koordinat pengesahan dan bukti foto kekal peribadi.",
    loginToCompare: "Log masuk untuk banding tempat diterokai",
    loginToCompareHint: "Log masuk dengan Google untuk banding penerokaan disahkan anda dengan {name}.",
    comparingPlaces: "Membanding tempat diterokai",
    comparisonNotYet: "Perbandingan belum tersedia",
    unableCompare: "Tidak dapat membanding tempat diterokai",
    coverageComparison: "Perbandingan liputan tarikan",
    exploredMaps: "Peta diterokai",
    exploredMapsHint: "Banding tarikan yang dicapai setiap pengembara melalui lawatan disahkan. Bukti pengesahan kekal peribadi.",
    yourExploredPlaces: "Tempat anda terokai",
    theirExploredPlaces: "Tempat terokai {name}",
    exploredByBoth: "Diterokai oleh kedua-dua pengembara",
    onlyExploredByYou: "Hanya diterokai oleh anda",
    onlyExploredByThem: "Hanya diterokai oleh {name}",
    you: "Anda",
    attractionsExplored: "{count} tarikan diterokai",
    exploredCount: "{count} diterokai",
    noVerifiedOnMap: "Tiada tarikan disahkan untuk dipaparkan pada peta ini.",
    noAttractionsInGroup: "Tiada tarikan dalam kumpulan ini.",
    dateUnavailable: "tarikh tidak tersedia",
    checkingAccess: "Menyemak akses",
    sectionUnavailable: "Bahagian ini tidak tersedia buat masa ini.",
    photosShowing: "Foto Dipaparkan",
    signInToLike: "Log masuk untuk suka",
    like: "Suka",
    liked: "Disukai",
    updating: "Mengemas kini...",
    unlikeReview: "Nyahsuka ulasan ini",
    likeReview: "Suka ulasan ini",
    signInToLikeReview: "Log masuk untuk suka ulasan ini",
    reviewed: "Mengulas",
    likeSingular: "suka",
    likePlural: "suka",
    locationAccessDenied: "Akses lokasi ditolak. Benarkan akses lokasi dan cuba lagi.",
    verificationPaused: "Pengesahan dijeda",
    setAsProfile: "Tetapkan sebagai profil",
    showDetails: "Paparkan Butiran",
    hideDetails: "Sembuyikan Butiran",
    locationAccessDenied: "Akses lokasi telah ditolak. Benarkan akses lokasi dan cuba lagi.",
    locationUnavailable: "Lokasi semasa anda tidak tersedia. Bergerak ke kawasan terbuka dan cuba lagi.",
    locationTimeout: "Masa tamat semasa cuba mengesan lokasi anda. Cuba semula di kawasan yang mempunyai isyarat yang jelas.",
    locationConfirmFailed: "Kami tidak dapat mengesahkan lokasi semasa anda. Sila cuba lagi.",
    cameraAccessDenied: "Akses kamera telah ditolak. Benarkan akses kamera dan cuba lagi.",
    cameraNotFound: "Kamera yang boleh digunakan tidak ditemui pada peranti ini.",
    cameraInUse: "Kamera tidak tersedia atau sedang digunakan. Tutup aplikasi kamera lain dan cuba lagi.",
    cameraOpenFailed: "Kami tidak dapat membuka kamera. Sila cuba lagi.",
    cameraUnavailableBrowser: "Rakaman kamera secara langsung tidak tersedia dalam pelayar ini.",
    locationUnavailableBrowser: "Lokasi semasa tidak tersedia dalam pelayar ini.",
    locationValidateFailed: "Kami tidak dapat mengesahkan lokasi semasa anda.",
    cameraCaptureFailed: "Imej kamera tidak dapat dirakam. Sila cuba lagi.",
    photoPreviewFailed: "Pratonton foto tidak dapat dihasilkan. Sila cuba lagi.",
    secureUploadFailed: "Muat naik selamat tidak dapat disediakan dalam pelayar ini. Sila cuba lagi.",
    verifyVisitFailed: "Kami tidak dapat mengesahkan kunjungan ini. Sila cuba lagi.",
    sessionExpiredSignIn: "Sesi anda telah tamat. Sila log masuk dan cuba lagi.",
    capacityCheckFailed: "Kami tidak dapat menyemak had foto hari ini. Sila cuba lagi.",
    verifiedVisitLimitReached: "Anda telah pun mengesahkan tarikan ini pada hari ini. Anda boleh menambah foto baharu pada tarikh lain di Malaysia.",
    uploadPhoto: "Muat naik foto",
    mustSignInToReview: "Anda mesti log masuk untuk menghantar ulasan.",
    signInViewVisited: "Log masuk untuk melihat lawatan anda yang telah disahkan",          
    signInViewVisitedHint: "Log masuk untuk melihat tempat yang disahkan melalui kunjungan anda yang telah disahkan.",      
    verifiedPhotosLoadError: "Ralat Memuatkan Foto Disahkan",
    verifiedPhotoDeleteError: "Ralat Pemadaman Foto Disahkan",
    signInViewProgress: "Log masuk untuk melihat kemajuan penerokaan",
    signInViewProgressHint: "Log masuk untuk menjejak kunjungan yang disahkan di lokasi tarikan yang disokong di Melaka.",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("chatlas-lang");
    if (saved && translations[saved]) {
      const restoreLanguageTimer = window.setTimeout(() => setLang(saved), 0);
      return () => window.clearTimeout(restoreLanguageTimer);
    }

    return undefined;
  }, []);

  const changeLang = (newLang) => {
    if (!translations[newLang]) return;
    setLang(newLang);
    localStorage.setItem("chatlas-lang", newLang);
  };

  const t = (key, vars = {}) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    Object.keys(vars).forEach((k) => {
      text = text.replaceAll(`{${k}}`, String(vars[k]));
    });
    return text;
  };

  const translateCategory = (name) => {
    if (!name || name === "All") return t("cat_All");
    const key = `cat_${name.replace(/\s+/g, "")}`;
    const translated = t(key);
    return translated !== key ? translated : name;
  };

  const translateState = (name) => {
    if (!name) return "";
    const key = `state_${name.replace(/\s+/g, "")}`;
    const translated = t(key);
    return translated !== key ? translated : name;
  };

  return (
    <LanguageContext.Provider
      value={{ lang, changeLang, t, translateCategory, translateState }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return ctx;
}
