"use client";

import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    // ——— Nav ———
    home: "Home",
    attractions: "Attractions",
    addAttraction: "+ Add Attraction",
    browseAttractions: "Browse Attractions",
    map: "Map",
    travellers: "Travellers",
    community: "Community",
    myProfile: "My Profile",
    logout: "Logout",
    signIn: "Sign in",
    menu: "Menu",

    // ——— Common ———
    loading: "Loading...",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    back: "Back",
    backToExplore: "Back to Explore",
    backToProfile: "Back to Profile",
    search: "Search",
    reset: "Reset",
    submit: "Submit",
    close: "Close",
    yes: "Yes",
    no: "No",
    errorGeneric: "Something went wrong. Please try again.",
    unauthorized: "Please sign in to continue.",
    notFound: "Page not found",

    // ——— Login ———
    loginSubtitle:
      "Sign in to save places, write reviews, and manage your profile",
    loginGuestHint:
      "You can still browse attractions, the map, and community as a guest.",
    signInWithGoogle: "Sign in with Google",
    signingIn: "Signing in...",
    continueAsGuest: "Continue browsing as guest",
    termsAgree: "By continuing, you agree to our Terms of Service",
    googleAuthFailed: "Google authentication failed. Please try again.",

    // ——— Home hero ———
    heroEyebrow: "Explore Melaka with the community",
    heroTitle: "Discover attractions and record your travel journey",
    heroSubtitle:
      "Browse popular and lesser-known attractions, read traveller experiences and start exploring Melaka.",

    // ——— Search / filters ———
    searchAttractions: "Search Attractions",
    searchPlaceholder: "Search attractions in Melaka",
    moreFilters: "More Filters",
    hideFilters: "Hide Filters",
    minimumRating: "Minimum Rating",
    anyRating: "Any Rating",
    ratingAndAbove: "and above",
    locationArea: "Location Area",
    allAreas: "All Areas",
    sortBy: "Sort by",
    sortNameAsc: "Name (A-Z)",
    sortRating: "Rating",
    sortNewest: "Newest",
    sortMostReviewed: "Most Reviewed",
    source: "Source",
    allAttractions: "All Attractions",
    communitySubmittedOnly: "Community-submitted only",
    allCategories: "All Categories",
    attractionsAvailable: "{count} attraction(s) available",
    resultsFound: "{count} result(s) found for {criteria}",
    loadingAttractions: "Loading attractions...",
    failedLoadAttractions: "Failed to load attractions. Please try again.",
    noAttractionsFound: "No attractions found",
    tryChangingFilters:
      "Try changing the keyword, category, area, rating, or clear all filters.",
    clearSearchAndFilters: "Clear Search and Filters",
    previous: "Previous",
    next: "Next",
    pageOf: "Page {page} of {total}",
    keyword: "keyword",
    category: "category",
    area: "area",
    rating: "rating",

    // ——— Categories (labels only; DB values stay English) ———
    cat_All: "All Categories",
    cat_Museum: "Museum",
    cat_Religious: "Religious",
    cat_TouristAttraction: "Tourist Attraction",
    cat_Historical: "Historical",
    cat_Nature: "Nature",
    cat_Entertainment: "Entertainment",
    cat_Gallery: "Gallery",

    // ——— Attraction detail / actions ———
    details: "Details",
    address: "Address",
    description: "Description",
    photos: "Photos",
    reviews: "Reviews",
    writeReview: "Write a review",
    addToWishlist: "Add to wishlist",
    removeFromWishlist: "Remove from wishlist",
    addToFavourites: "Add to favourites",
    removeFromFavourites: "Remove from favourites",
    signInToSave: "Sign in to save this place",
    signInToReview: "Sign in to write a review",
    editDescription: "Edit description",
    saveDescription: "Save description",
    onlyMelakaCanEdit:
      "Only users whose home state is Melaka can edit descriptions.",
    uploadPhoto: "Upload photo",
    noPhotosYet: "No photos yet",
    noReviewsYetAttraction: "No reviews yet",
    communitySubmitted: "Community submitted",
    openInMaps: "Open in maps",

    // ——— Add attraction ———
    addAttractionTitle: "Add Attraction",
    attractionName: "Name",
    attractionCategory: "Category",
    attractionAddress: "Address",
    attractionDescriptionOptional: "Description (optional)",
    submitAttraction: "Submit attraction",
    submitSuccess: "Attraction submitted successfully",
    submitFailed: "Failed to submit attraction",
    signInToAddAttraction: "Sign in to add an attraction",

    // ——— Profile ———
    editProfile: "Edit Profile",
    displayName: "Display name",
    email: "Email",
    location: "Location",
    homeState: "Home state",
    selectStateTerritory: "Select state / territory",
    locationLegacyHint:
      'Previous value "{value}" is not in the list. Please choose a state or territory above.',
    melakaEditHint: "You can edit Melaka attraction descriptions.",
    bio: "Bio",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated successfully!",
    memberSince: "Member since",
    placesVisited: "Places visited",
    reviewsWritten: "Reviews written",
    photosUploaded: "Photos uploaded",
    savedPlaces: "Saved places",
    yourCollection: "Your Collection",
    wishlist: "Wishlist",
    favourites: "Favourites",
    myReviews: "My Reviews",
    myPhotos: "My Photos",
    travelHistory: "Travel History",
    recentReviews: "Recent Reviews",
    noReviewsYet: "You haven't written any reviews yet.",
    youHaveReviews: "You have {count} reviews.",
    locationLabel: "Location",
    itemsSaved: "items saved",
    reviewsWrittenCount: "reviews written",
    photosUploadedCount: "photos uploaded",
    locationPlaceholder: "City or region you explore from",
    bioPlaceholder: "A short introduction shown on your public profile",
    fileTooLarge: "File is too large. Maximum size is 5MB.",
    unsupportedFormat:
      "Unsupported file format. Please upload JPG, PNG, or WEBP.",
    uploadHint: "JPG, PNG or WEBP, max 5MB",

    // ——— Community / reviews ———
    communityTitle: "Community",
    allReviews: "All reviews",
    latestReviews: "Latest reviews",
    reviewSortNewest: "Newest",
    reviewSortOldest: "Oldest",
    reviewSortHighestRating: "Highest Rating",
    reviewSortLowestRating: "Lowest Rating",
    reviewSortMostLiked: "Most Liked",
    communityFilterLabel: "Filter reviews",
    communityFilterAll: "All Reviews",
    communityFilterWithPhotos: "With Photos",
    communityFilterHighlyRated: "4 Stars & Above",
    communitySearchPlaceholder: "Search review text or attractions",
    communityEmpty: "No community reviews yet.",
    communitySearchEmpty: 'No reviews found for "{query}".',
    communityPhotosEmpty: "No reviews with photos found.",
    communityHighlyRatedEmpty: "No highly rated reviews found.",
    communityClearSearch: "Clear search",
    communityRetry: "Retry",
    communityViewAttraction: "View attraction",
    communityPaginationLabel: "Community review pages",
    communityGoToPage: "Go to page {page}",
    selected: "Selected",
    yourRating: "Your rating",
    reviewPlaceholder: "Share your experience...",
    postReview: "Post review",
    editReview: "Edit review",
    photosShowing: "Showing {count} photo(s)",
    currentProfilePicture: "Current profile picture",
    setAsProfile: "Set as profile",
    settingProfile: "Setting...",
    editedAt: "Edited: {date}",
    readyToEdit: "Ready to edit",
    daysUntilEdit: "{count} days until edit",
    deleteReview: "Delete review",
    confirmDeleteReview: "Delete this review?",
    reviewPosted: "Review posted",
    noCommunityReviews: "No reviews yet. Be the first to share.",
    stars: "stars",

    // ——— Map ———
    mapTitle: "Exploration Map",
    mapLoading: "Loading map...",
    mapFailed: "Failed to load map",
    showAll: "Show all",
    visited: "Visited",
    notVisited: "Not visited",
    exploreProgress: "Exploration progress",
    signInForMapFeatures: "Sign in to track places you've visited",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",

    // ——— Travellers / social ———
    travellersTitle: "Travellers",
    searchTravellers: "Search travellers",
    publicProfile: "Public profile",
    noTravellersFound: "No travellers found",
    compareVisits: "Compare visits",
    commonPlaces: "Places in common",
    differentPlaces: "Different places",
    viewProfile: "View profile",

    // ——— Collection pages ———
    wishlistTitle: "Wishlist",
    favouritesTitle: "Favourites",
    myPhotosTitle: "My Photos",
    travelHistoryTitle: "Travel History",
    emptyWishlist: "Your wishlist is empty",
    emptyFavourites: "No favourites yet",
    emptyPhotos: "No photos uploaded yet",
    emptyHistory: "No travel history yet",
    remove: "Remove",

    // ——— States (UI labels; stored values stay English) ———
    state_Johor: "Johor",
    state_Kedah: "Kedah",
    state_Kelantan: "Kelantan",
    state_Melaka: "Melaka",
    state_NegeriSembilan: "Negeri Sembilan",
    state_Pahang: "Pahang",
    state_Penang: "Penang",
    state_Perak: "Perak",
    state_Perlis: "Perlis",
    state_Sabah: "Sabah",
    state_Sarawak: "Sarawak",
    state_Selangor: "Selangor",
    state_Terengganu: "Terengganu",
    state_KualaLumpur: "Kuala Lumpur",
    state_Labuan: "Labuan",
    state_Putrajaya: "Putrajaya",
  },

  zh: {
    home: "首页",
    attractions: "景点",
    addAttraction: "+ 添加景点",
    browseAttractions: "浏览景点",
    map: "地图",
    travellers: "旅人",
    community: "社区",
    myProfile: "我的资料",
    logout: "登出",
    signIn: "登录",
    menu: "菜单",

    loading: "加载中...",
    cancel: "取消",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    view: "查看",
    back: "返回",
    backToExplore: "返回探索",
    backToProfile: "返回个人资料",
    search: "搜索",
    reset: "重置",
    submit: "提交",
    close: "关闭",
    yes: "是",
    no: "否",
    errorGeneric: "出错了，请重试。",
    unauthorized: "请先登录。",
    notFound: "页面不存在",

    loginSubtitle: "登录以收藏地点、撰写评价并管理个人资料",
    loginGuestHint: "未登录仍可浏览景点、地图和社区。",
    signInWithGoogle: "使用 Google 登录",
    signingIn: "登录中...",
    continueAsGuest: "以访客身份继续浏览",
    termsAgree: "继续即表示同意服务条款",
    googleAuthFailed: "Google 登录失败，请重试。",

    heroEyebrow: "与社区一起探索马六甲",
    heroTitle: "发现景点，记录你的旅行足迹",
    heroSubtitle:
      "浏览热门与小众景点，阅读旅人分享，开始探索马六甲。",

    searchAttractions: "搜索景点",
    searchPlaceholder: "在马六甲搜索景点",
    moreFilters: "更多筛选",
    hideFilters: "收起筛选",
    minimumRating: "最低评分",
    anyRating: "不限评分",
    ratingAndAbove: "及以上",
    locationArea: "区域",
    allAreas: "全部区域",
    sortBy: "排序方式",
    sortNameAsc: "名称 (A-Z)",
    sortRating: "评分",
    sortNewest: "最新",
    sortMostReviewed: "评价最多",
    source: "来源",
    allAttractions: "全部景点",
    communitySubmittedOnly: "仅社区提交",
    allCategories: "全部分类",
    attractionsAvailable: "共 {count} 个景点",
    resultsFound: "找到 {count} 个结果：{criteria}",
    loadingAttractions: "正在加载景点...",
    failedLoadAttractions: "加载景点失败，请重试。",
    noAttractionsFound: "未找到景点",
    tryChangingFilters:
      "请尝试更改关键词、分类、区域、评分，或清除所有筛选。",
    clearSearchAndFilters: "清除搜索与筛选",
    previous: "上一页",
    next: "下一页",
    pageOf: "第 {page} / {total} 页",
    keyword: "关键词",
    category: "分类",
    area: "区域",
    rating: "评分",

    cat_All: "全部分类",
    cat_Museum: "博物馆",
    cat_Religious: "宗教",
    cat_TouristAttraction: "旅游景点",
    cat_Historical: "历史",
    cat_Nature: "自然",
    cat_Entertainment: "娱乐",
    cat_Gallery: "画廊",

    details: "详情",
    address: "地址",
    description: "简介",
    photos: "照片",
    reviews: "评价",
    writeReview: "写评价",
    addToWishlist: "加入心愿单",
    removeFromWishlist: "移出心愿单",
    addToFavourites: "加入收藏",
    removeFromFavourites: "取消收藏",
    signInToSave: "登录以收藏此地",
    signInToReview: "登录以撰写评价",
    editDescription: "编辑简介",
    saveDescription: "保存简介",
    onlyMelakaCanEdit: "仅家在马六甲的用户可编辑简介。",
    uploadPhoto: "上传照片",
    noPhotosYet: "暂无照片",
    noReviewsYetAttraction: "暂无评价",
    communitySubmitted: "社区提交",
    openInMaps: "在地图中打开",

    addAttractionTitle: "添加景点",
    attractionName: "名称",
    attractionCategory: "分类",
    attractionAddress: "地址",
    attractionDescriptionOptional: "简介（可选）",
    submitAttraction: "提交景点",
    submitSuccess: "景点提交成功",
    submitFailed: "提交失败",
    signInToAddAttraction: "登录以添加景点",

    editProfile: "编辑资料",
    displayName: "显示名称",
    email: "邮箱",
    location: "所在地",
    homeState: "所在州属",
    selectStateTerritory: "选择州属 / 联邦直辖区",
    locationLegacyHint:
      "原值「{value}」不在列表中，请重新选择州属。",
    melakaEditHint: "你可以编辑马六甲景点的简介。",
    bio: "简介",
    saveChanges: "保存修改",
    saving: "保存中...",
    profileUpdated: "资料更新成功！",
    memberSince: "加入于",
    placesVisited: "已访问地点",
    reviewsWritten: "已写评价",
    photosUploaded: "已上传照片",
    savedPlaces: "已收藏地点",
    yourCollection: "我的收藏",
    wishlist: "心愿单",
    favourites: "收藏",
    myReviews: "我的评价",
    myPhotos: "我的照片",
    travelHistory: "旅行历史",
    recentReviews: "最近评价",
    noReviewsYet: "你还没有写过任何评价。",
    youHaveReviews: "你有 {count} 条评价。",
    locationLabel: "所在地",
    itemsSaved: "项已保存",
    reviewsWrittenCount: "条评价",
    photosUploadedCount: "张照片",
    locationPlaceholder: "你常探索的城市或地区",
    bioPlaceholder: "展示在公开资料上的简短介绍",
    fileTooLarge: "文件过大，最大 5MB。",
    unsupportedFormat: "不支持的格式，请上传 JPG、PNG 或 WEBP。",
    uploadHint: "JPG、PNG 或 WEBP，最大 5MB",

    communityTitle: "社区",
    allReviews: "全部评价",
    latestReviews: "最新评价",
    reviewSortNewest: "最新",
    reviewSortOldest: "最早",
    reviewSortHighestRating: "评分最高",
    reviewSortLowestRating: "评分最低",
    reviewSortMostLiked: "最多赞",
    communityFilterLabel: "筛选评价",
    communityFilterAll: "全部评价",
    communityFilterWithPhotos: "含照片",
    communityFilterHighlyRated: "4 星及以上",
    communitySearchPlaceholder: "搜索评价内容或景点",
    communityEmpty: "暂无社区评价。",
    communitySearchEmpty: "未找到有关“{query}”的评价。",
    communityPhotosEmpty: "未找到含照片的评价。",
    communityHighlyRatedEmpty: "未找到高评分评价。",
    communityClearSearch: "清除搜索",
    communityRetry: "重试",
    communityViewAttraction: "查看景点",
    communityPaginationLabel: "社区评价分页",
    communityGoToPage: "前往第 {page} 页",
    selected: "已选择",
    yourRating: "你的评分",
    reviewPlaceholder: "分享你的体验...",
    postReview: "发布评价",
    editReview: "编辑评价",
    photosShowing: "显示 {count} 张照片",
    currentProfilePicture: "当前个人头像",
    setAsProfile: "设为个人头像",
    settingProfile: "设置中...",
    editedAt: "已编辑：{date}",
    readyToEdit: "可编辑",
    daysUntilEdit: "距下次编辑还有 {count} 天",
    deleteReview: "删除评价",
    confirmDeleteReview: "确定删除这条评价？",
    reviewPosted: "评价已发布",
    noCommunityReviews: "还没有评价，来当第一个分享的人吧。",
    stars: "星",

    mapTitle: "探索地图",
    mapLoading: "地图加载中...",
    mapFailed: "地图加载失败",
    showAll: "显示全部",
    visited: "已去过",
    notVisited: "未去过",
    exploreProgress: "探索进度",
    signInForMapFeatures: "登录以记录去过的地点",
    zoomIn: "放大",
    zoomOut: "缩小",

    travellersTitle: "旅人",
    searchTravellers: "搜索旅人",
    publicProfile: "公开资料",
    noTravellersFound: "未找到旅人",
    compareVisits: "对比足迹",
    commonPlaces: "共同去过",
    differentPlaces: "不同足迹",
    viewProfile: "查看资料",

    wishlistTitle: "心愿单",
    favouritesTitle: "收藏",
    myPhotosTitle: "我的照片",
    travelHistoryTitle: "旅行历史",
    emptyWishlist: "心愿单是空的",
    emptyFavourites: "暂无收藏",
    emptyPhotos: "尚未上传照片",
    emptyHistory: "暂无旅行记录",
    remove: "移除",

    state_Johor: "柔佛",
    state_Kedah: "吉打",
    state_Kelantan: "吉兰丹",
    state_Melaka: "马六甲",
    state_NegeriSembilan: "森美兰",
    state_Pahang: "彭亨",
    state_Penang: "槟城",
    state_Perak: "霹雳",
    state_Perlis: "玻璃市",
    state_Sabah: "沙巴",
    state_Sarawak: "砂拉越",
    state_Selangor: "雪兰莪",
    state_Terengganu: "登嘉楼",
    state_KualaLumpur: "吉隆坡",
    state_Labuan: "纳闽",
    state_Putrajaya: "布城",
  },

  ms: {
    home: "Laman Utama",
    attractions: "Tarikan",
    addAttraction: "+ Tambah Tarikan",
    browseAttractions: "Lihat Tarikan",
    map: "Peta",
    travellers: "Pengembara",
    community: "Komuniti",
    myProfile: "Profil Saya",
    logout: "Log Keluar",
    signIn: "Log Masuk",
    menu: "Menu",

    loading: "Memuatkan...",
    cancel: "Batal",
    save: "Simpan",
    delete: "Padam",
    edit: "Edit",
    view: "Lihat",
    back: "Kembali",
    backToExplore: "Kembali ke Teroka",
    backToProfile: "Kembali ke Profil",
    search: "Cari",
    reset: "Set Semula",
    submit: "Hantar",
    close: "Tutup",
    yes: "Ya",
    no: "Tidak",
    errorGeneric: "Berlaku ralat. Sila cuba lagi.",
    unauthorized: "Sila log masuk untuk teruskan.",
    notFound: "Halaman tidak dijumpai",

    loginSubtitle:
      "Log masuk untuk simpan tempat, tulis ulasan dan urus profil",
    loginGuestHint:
      "Anda masih boleh layari tarikan, peta dan komuniti sebagai tetamu.",
    signInWithGoogle: "Log masuk dengan Google",
    signingIn: "Sedang log masuk...",
    continueAsGuest: "Teruskan melayari sebagai tetamu",
    termsAgree:
      "Dengan meneruskan, anda bersetuju dengan Terma Perkhidmatan kami",
    googleAuthFailed: "Pengesahan Google gagal. Sila cuba lagi.",

    heroEyebrow: "Terokai Melaka bersama komuniti",
    heroTitle: "Temui tarikan dan rekod perjalanan anda",
    heroSubtitle:
      "Layari tarikan popular dan tersembunyi, baca pengalaman pengembara dan mula terokai Melaka.",

    searchAttractions: "Cari Tarikan",
    searchPlaceholder: "Cari tarikan di Melaka",
    moreFilters: "Lagi Penapis",
    hideFilters: "Sembunyikan Penapis",
    minimumRating: "Penilaian Minimum",
    anyRating: "Sebarang Penilaian",
    ratingAndAbove: "dan ke atas",
    locationArea: "Kawasan",
    allAreas: "Semua Kawasan",
    sortBy: "Susun mengikut",
    sortNameAsc: "Nama (A-Z)",
    sortRating: "Penilaian",
    sortNewest: "Terbaharu",
    sortMostReviewed: "Paling Banyak Diulas",
    source: "Sumber",
    allAttractions: "Semua Tarikan",
    communitySubmittedOnly: "Hanya diserahkan komuniti",
    allCategories: "Semua Kategori",
    attractionsAvailable: "{count} tarikan tersedia",
    resultsFound: "{count} keputusan dijumpai untuk {criteria}",
    loadingAttractions: "Memuatkan tarikan...",
    failedLoadAttractions: "Gagal memuatkan tarikan. Sila cuba lagi.",
    noAttractionsFound: "Tiada tarikan dijumpai",
    tryChangingFilters:
      "Cuba ubah kata kunci, kategori, kawasan, penilaian, atau kosongkan semua penapis.",
    clearSearchAndFilters: "Kosongkan Carian dan Penapis",
    previous: "Sebelum",
    next: "Seterusnya",
    pageOf: "Halaman {page} daripada {total}",
    keyword: "kata kunci",
    category: "kategori",
    area: "kawasan",
    rating: "penilaian",

    cat_All: "Semua Kategori",
    cat_Museum: "Muzium",
    cat_Religious: "Agama",
    cat_TouristAttraction: "Tarikan Pelancong",
    cat_Historical: "Sejarah",
    cat_Nature: "Alam",
    cat_Entertainment: "Hiburan",
    cat_Gallery: "Galeri",

    details: "Butiran",
    address: "Alamat",
    description: "Penerangan",
    photos: "Foto",
    reviews: "Ulasan",
    writeReview: "Tulis ulasan",
    addToWishlist: "Tambah ke senarai hajat",
    removeFromWishlist: "Buang dari senarai hajat",
    addToFavourites: "Tambah ke kegemaran",
    removeFromFavourites: "Buang dari kegemaran",
    signInToSave: "Log masuk untuk simpan tempat ini",
    signInToReview: "Log masuk untuk tulis ulasan",
    editDescription: "Edit penerangan",
    saveDescription: "Simpan penerangan",
    onlyMelakaCanEdit:
      "Hanya pengguna yang negeri asal Melaka boleh edit penerangan.",
    uploadPhoto: "Muat naik foto",
    noPhotosYet: "Tiada foto lagi",
    noReviewsYetAttraction: "Tiada ulasan lagi",
    communitySubmitted: "Diserahkan komuniti",
    openInMaps: "Buka dalam peta",

    addAttractionTitle: "Tambah Tarikan",
    attractionName: "Nama",
    attractionCategory: "Kategori",
    attractionAddress: "Alamat",
    attractionDescriptionOptional: "Penerangan (pilihan)",
    submitAttraction: "Hantar tarikan",
    submitSuccess: "Tarikan berjaya dihantar",
    submitFailed: "Gagal menghantar tarikan",
    signInToAddAttraction: "Log masuk untuk tambah tarikan",

    editProfile: "Edit Profil",
    displayName: "Nama paparan",
    email: "E-mel",
    location: "Lokasi",
    homeState: "Negeri asal",
    selectStateTerritory: "Pilih negeri / wilayah persekutuan",
    locationLegacyHint:
      'Nilai lama "{value}" tiada dalam senarai. Sila pilih negeri di atas.',
    melakaEditHint: "Anda boleh edit penerangan tarikan Melaka.",
    bio: "Bio",
    saveChanges: "Simpan perubahan",
    saving: "Menyimpan...",
    profileUpdated: "Profil berjaya dikemas kini!",
    memberSince: "Ahli sejak",
    placesVisited: "Tempat dilawati",
    reviewsWritten: "Ulasan ditulis",
    photosUploaded: "Foto dimuat naik",
    savedPlaces: "Tempat disimpan",
    yourCollection: "Koleksi Anda",
    wishlist: "Senarai Hajat",
    favourites: "Kegemaran",
    myReviews: "Ulasan Saya",
    myPhotos: "Foto Saya",
    travelHistory: "Sejarah Perjalanan",
    recentReviews: "Ulasan Terkini",
    noReviewsYet: "Anda belum menulis sebarang ulasan.",
    youHaveReviews: "Anda mempunyai {count} ulasan.",
    locationLabel: "Lokasi",
    itemsSaved: "item disimpan",
    reviewsWrittenCount: "ulasan ditulis",
    photosUploadedCount: "foto dimuat naik",
    locationPlaceholder: "Bandar atau kawasan yang anda terokai",
    bioPlaceholder: "Pengenalan ringkas pada profil awam anda",
    fileTooLarge: "Fail terlalu besar. Maksimum 5MB.",
    unsupportedFormat:
      "Format tidak disokong. Sila muat naik JPG, PNG, atau WEBP.",
    uploadHint: "JPG, PNG atau WEBP, maks 5MB",

    communityTitle: "Komuniti",
    allReviews: "Semua ulasan",
    latestReviews: "Ulasan terkini",
    reviewSortNewest: "Terbaharu",
    reviewSortOldest: "Terlama",
    reviewSortHighestRating: "Penilaian Tertinggi",
    reviewSortLowestRating: "Penilaian Terendah",
    reviewSortMostLiked: "Paling Disukai",
    communityFilterLabel: "Tapis ulasan",
    communityFilterAll: "Semua Ulasan",
    communityFilterWithPhotos: "Dengan Foto",
    communityFilterHighlyRated: "4 Bintang & Ke Atas",
    communitySearchPlaceholder: "Cari teks ulasan atau tarikan",
    communityEmpty: "Belum ada ulasan komuniti.",
    communitySearchEmpty: 'Tiada ulasan dijumpai untuk "{query}".',
    communityPhotosEmpty: "Tiada ulasan dengan foto dijumpai.",
    communityHighlyRatedEmpty: "Tiada ulasan berpenilaian tinggi dijumpai.",
    communityClearSearch: "Kosongkan carian",
    communityRetry: "Cuba lagi",
    communityViewAttraction: "Lihat tarikan",
    communityPaginationLabel: "Halaman ulasan komuniti",
    communityGoToPage: "Pergi ke halaman {page}",
    selected: "Dipilih",
    yourRating: "Penilaian anda",
    reviewPlaceholder: "Kongsi pengalaman anda...",
    postReview: "Siarkan ulasan",
    editReview: "Edit ulasan",
    photosShowing: "Memaparkan {count} foto",
    currentProfilePicture: "Gambar profil semasa",
    setAsProfile: "Tetapkan sebagai gambar profil",
    settingProfile: "Menetapkan...",
    editedAt: "Diedit: {date}",
    readyToEdit: "Sedia untuk diedit",
    daysUntilEdit: "{count} hari lagi untuk mengedit",
    deleteReview: "Padam ulasan",
    confirmDeleteReview: "Padam ulasan ini?",
    reviewPosted: "Ulasan disiar",
    noCommunityReviews: "Tiada ulasan lagi. Jadilah yang pertama.",
    stars: "bintang",

    mapTitle: "Peta Penerokaan",
    mapLoading: "Memuatkan peta...",
    mapFailed: "Gagal memuatkan peta",
    showAll: "Papar semua",
    visited: "Dilawati",
    notVisited: "Belum dilawati",
    exploreProgress: "Kemajuan penerokaan",
    signInForMapFeatures: "Log masuk untuk jejak tempat dilawati",
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",

    travellersTitle: "Pengembara",
    searchTravellers: "Cari pengembara",
    publicProfile: "Profil awam",
    noTravellersFound: "Tiada pengembara dijumpai",
    compareVisits: "Banding lawatan",
    commonPlaces: "Tempat sama",
    differentPlaces: "Tempat berbeza",
    viewProfile: "Lihat profil",

    wishlistTitle: "Senarai Hajat",
    favouritesTitle: "Kegemaran",
    myPhotosTitle: "Foto Saya",
    travelHistoryTitle: "Sejarah Perjalanan",
    emptyWishlist: "Senarai hajat kosong",
    emptyFavourites: "Tiada kegemaran lagi",
    emptyPhotos: "Belum muat naik foto",
    emptyHistory: "Tiada sejarah perjalanan",
    remove: "Buang",

    state_Johor: "Johor",
    state_Kedah: "Kedah",
    state_Kelantan: "Kelantan",
    state_Melaka: "Melaka",
    state_NegeriSembilan: "Negeri Sembilan",
    state_Pahang: "Pahang",
    state_Penang: "Pulau Pinang",
    state_Perak: "Perak",
    state_Perlis: "Perlis",
    state_Sabah: "Sabah",
    state_Sarawak: "Sarawak",
    state_Selangor: "Selangor",
    state_Terengganu: "Terengganu",
    state_KualaLumpur: "Kuala Lumpur",
    state_Labuan: "Labuan",
    state_Putrajaya: "Putrajaya",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("chatlas-lang");
    if (saved && translations[saved]) {
      const restoreLanguageTimer = window.setTimeout(() => setLang(saved), 0);
      return () => window.clearTimeout(restoreLanguageTimer);
    }

    return undefined;
  }, []);

  const changeLang = (newLang) => {
    if (!translations[newLang]) return;
    setLang(newLang);
    localStorage.setItem("chatlas-lang", newLang);
  };

  const t = (key, vars = {}) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    Object.keys(vars).forEach((k) => {
      text = text.replaceAll(`{${k}}`, String(vars[k]));
    });
    return text;
  };

  const translateCategory = (name) => {
    if (!name || name === "All") return t("cat_All");
    const key = `cat_${name.replace(/\s+/g, "")}`;
    const translated = t(key);
    return translated !== key ? translated : name;
  };

  const translateState = (name) => {
    if (!name) return "";
    const key = `state_${name.replace(/\s+/g, "")}`;
    const translated = t(key);
    return translated !== key ? translated : name;
  };

  return (
    <LanguageContext.Provider
      value={{ lang, changeLang, t, translateCategory, translateState }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return ctx;
}
